#数据库连接池
#spring:
#  datasource:
#    username: root
#    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://bootzhong.top:3306/TS_Platform?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
#
spring:
  datasource:
    username: ENC(JUj0I76WRQIWrZa1bJj8Og0LAmlUi4zS)
    password: ENC(S9wJL+/9zyKw+wHtMcIBpXDS6cmcM8rVSTJU13NyfSA=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Iin72SzbDDMw49y6EwyuPqiztQcbZJiGOjMp5pa4Ol7z3RMfhmmBU/vKXe/hbZx/1tZG1XnGGbxK9+UC9QZ+8SKZiZdxT5ev5v5Vt7Lv8nvtFIeRRNQa3rVDqTSrDY9rHH59oxkXIm503J2/M08rcw==)
    hikari:
      max-lifetime: 500000

#mybatis xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

